### ISSUE TITLE
How to get message uid?

### ISSUE THREAD

**Issue by HZSamir** [MateMalice/mail-listener2#19]
Hi,
I'm trying to get a message's uid, old example suggest:

```javascript
mailListener.on("mail", function (mail, seqno, attributes) {
  const uid = attributes.uid;
});
```

However it seems `attributes` does not exist here.
Thank you

**Comment by thechampl** [comment]
Hi also having this issue above, can not get attributes.uid in order to move an email to a different mailbox once I have parsed it.  Is there another way to get the uid from the message?  I could not find it in the mail object.  Thanks

**Comment by Nitair** [comment]
This has been accidentally removed by using a different parser. You can fix that by the following change:

Add under `f.on('message', (msg, seqno)`

```
let attributes = null
msg.on('attributes', (attrs) => {
  attributes = attrs;
});
```

change from `self.emit('mail', parsed, seqno);` to `self.emit('mail', parsed, seqno, attributes);`

Now you can use it on the method 

```
mailListener.on('mail', (mail, seqno, attr) => {
  console.log(attr);
  // For UID
  console.log(attr.uid);
});
```

I will create a PR for it soon.
