### ISSUE TITLE
npm audit vulnerability

### ISSUE THREAD

**Issue by alex737876** [MateMalice/mail-listener2#36]
Running npm audit on a project using mail-listener2, gives following hint:

**Comment by alex737876** [comment]
nodemailer  <=6.6.0
Severity: critical
Header injection in nodemailer - https://github.com/advisories/GHSA-hwqf-gcqm-7353
Command injection in nodemailer - https://github.com/advisories/GHSA-48ww-j4fc-435p
No fix available
node_modules/nodemailer
  mailparser  2.3.1 - 3.2.0
  Depends on vulnerable versions of nodemailer
  node_modules/mailparser
    mail-listener5  *
    Depends on vulnerable versions of mailparser
    node_modules/mail-listener5

**Comment by MateMalice** [comment]
Fixed in [v2.1.1](https://github.com/MateMalice/mail-listener2/releases/tag/v2.1.1).
