### ISSUE TITLE
TypeError: MailListener is not a constructor

### ISSUE THREAD

**Issue by paragkulkarni** [MateMalice/mail-listener2#7]
TypeError: MailListener is not a constructor

Please solve this error

**Comment by MateMalice** [comment]
Hi paragkulkarni,

Are you using the syntax in the previous version of the README for requiring the module, namely:
```javascript
var MailListener = require('mail-listener5');
```
?

If so, then this will not work, as the class is exported as a property of the package. This is a mistake in the README that I will shortly fix. I could also change the way the module is exported, but that would be a breaking change for others using the package. :-) 

To require the module, use one of the following methods:
```javascript
var MailListener = require('mail-listener5').MailListener;    // If you look at test.js in the root directory of the repo, you'll see that this is how the module is imported there
```
OR
```javascript
var { MailListener } = require('mail-listener5');    // This won't work with versions of JS before ES6 that do not support destructuring
```

Closing this as I suspect this will solve your issue. If not, feel free to open another. :-)
